version: '3'
services:
  # nodes
  node1:
    image: mongo
    hostname: node1
    expose:
      - '27017'
    volumes:
      - ./node1:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n1' ]
  node11:
    image: mongo
    hostname: node11
    expose:
      - '27017'
    volumes:
      - ./node11:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n1' ]
  node2:
    image: mongo
    hostname: node2
    expose:
      - '27017'
    volumes:
      - ./node2:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n2' ]
  node21:
    image: mongo
    hostname: node21
    expose:
      - '27017'
    volumes:
      - ./node21:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n2' ]
  node3:
    image: mongo
    hostname: node3
    expose:
      - '27017'
    volumes:
      - ./node3:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n3' ]
  node31:
    image: mongo
    hostname: node31
    expose:
      - '27017'
    volumes:
      - ./node31:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n3' ]
  node4:
    image: mongo
    hostname: node4
    expose:
      - '27017'
    volumes:
      - ./node4:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n4' ]
  node41:
    image: mongo
    hostname: node41
    expose:
      - '27017'
    volumes:
      - ./node41:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n4' ]
  node5:
    image: mongo
    hostname: node5
    expose:
      - '27017'
    volumes:
      - ./node5:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n5' ]
  node51:
    image: mongo
    hostname: node51
    expose:
      - '27017'
    volumes:
      - ./node51:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n5' ]
  node6:
    image: mongo
    hostname: node6
    expose:
      - '27017'
    volumes:
      - ./node6:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n6' ]
  node61:
    image: mongo
    hostname: node61
    expose:
      - '27017'
    volumes:
      - ./node61:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--shardsvr', '--port', '27017', '--replSet', 'n6' ]
  # mongos
  mongos1:
    image: mongo
    hostname: mongos1
    expose:
      - '27017'
    links:
      - node1:node1
      - node2:node2
      - config1:config1
    volumes:
      - ./mongos:/data/db
    restart: always
    entrypoint: [ '/usr/bin/mongos', '--configdb', 'cfg1/config1:27017', '--port', '27017' ]
  # config 
  config1:
    image: mongo
    hostname: config1
    expose:
      - '27017'
    volumes:
      - ./config:/data/configdb
    restart: always
    entrypoint: [ '/usr/bin/mongod', '--configsvr', '--port', '27017', '--replSet', 'cfg1' ]
    # need to initiate the replicate set
  # setup
  mongosetup:
    image: mongo
    expose:
      - '27017'
    links:
      - node1:node1
      - node2:node2
      - config1:config1
      - mongos1:mongos1
    restart: always